### PR TITLE
Makes comments and formatting consistent

### PR DESCRIPTION
**Pull request by gigamesh**
Please don't be alarmed by the diff. None of the changes will change the bytecode.

Given the significance of EIP-4337 and how much use these contracts will receive, I thought it would be beneficial to make the comments more consistently natspec compliant and make the line lengths & indentation consistent for better readability. I tried not to be too opinionated and followed established patterns (used same @param description indentation pattern as [Seaport](https://github.com/ProjectOpenSea/seaport)). 

Summary:
- Limits line character count 
- Indentation consistency
- Punctuation consistency
- Consistent natspec formatting 
  - Adds missing `@param` descriptions
  - Uses `@inheritdoc` for the functions that can use it but weren't already
- Makes multiline comments use `/***/`

I'm happy to make any changes. And if you prefer to not merge this, no problem. 

Note: I didn't touch any of the contracts in `/samples` and `/test` but happy to do those as well. Also didn't add descriptions for events, errors, `constructor` and `receive` functions that are missing them.

### CODE REVIEW

**Comment by gigamesh** [comment]
Alright well I guess this is just going to get ignored. 😞

**Comment by shahafn** [comment]
Hi @gigamesh sorry for not responding earlier. We'll review the PR. Thank you for the effort!

**Comment by drortirosh** [comment]
Thank you.
we will merge it, but only before next release, as we want to keep the contracts compatible with the on-chain contracts, and any source change (even comment) generates slight different bytecode..

**Comment by gigamesh** [comment]
> Thank you. we will merge it, but only before next release, as we want to keep the contracts compatible with the on-chain contracts, and any source change (even comment) generates slight different bytecode..

Much appreciated!

**Review by forshtat — APPROVED** [review]

**Pull request merged**
