### PR TITLE
add `virtual` to EntryPoint functions

### PR DESCRIPTION
**Pull request by taxio**
Thanks for the wonderful implementation and library.

EntryPoint is very complex, so when creating an extended EntryPoint with a specific context, I want to base it as much as possible on your implementation.

Therefore, I added `virtual` to the EntryPoint functions so that I can override each method.

### CODE REVIEW

**Comment by shahafn** [comment]
EntryPoint is supposed to be a known singleton contract. Can you please elaborate on why you'd need to extend and deploy your own EntryPoint?

**Comment by drortirosh** [comment]
yes. the entrypoint is deployed as a singleton. if you always modify the code locally to have your own, but it is discouraged.

**Comment by yoavw** [comment]
@taxio since EntryPoint is a singleton and there should be only one per blockchain, it would be good if you share what you think is missing from it.  If you deploy a separate one, any account that uses it will be incompatible with the mempool so bundlers will not propagate its transactions.  If something is missing from EntryPoint, it would be better to discuss it and see if it should be added to the singleton.

**Comment by taxio** [comment]
Thank you everyone for your comments. I didn't realize that EntryPoint is a singleton.

I casually submitted a PR thinking that various extended EntryPoints would appear for each business idea, but considering it's a singleton, I should have discussed whether or not to include the functionality in EntryPoint itself.

**Pull request closed without merging**
